### ISSUE TITLE
shape.ShapeInput not defined

### ISSUE THREAD

**Issue by akkana** [python-xlib/python-xlib#78] opened 2017-04-01 00:47 UTC
I'm trying to set the input shape, with the Python equivalent of the C
    XShapeCombineMask(dpy, win, ShapeInput, 0, 0, my_input_pm, ShapeSet);

I expected, based on the shapewin.py example, that would translate to something like
    self.window.shape_mask(shape.ShapeUnion, shape.ShapeInput,
                                   0, [something], self.my_input_pm)

But there's no shape.ShapeInput defined, and passing 2 (the definition of ShapeInput in <X11/extensions/shapeconst.h> raises ValueError: field region: argument 2 not in (0, 1).

Is there a way to set the input shape in Python? The C version works but I'd much rather use Python.

**Comment by benoit-pierre** [comment] 2017-04-01 01:32
Update to `>=0.16`: the SHAPE extension was rewritten for the license change ([release notes](https://github.com/python-xlib/python-xlib/releases/tag/0.16)), and the [missing field is now present](https://github.com/python-xlib/python-xlib/blob/master/Xlib/ext/shape.py#L21).

Check [`shapewin.py`](https://github.com/python-xlib/python-xlib/blob/master/examples/shapewin.py) for an example of the new API, and `/usr/share/xcb/shape.xml` for the full specification (the code was generated from there).

**Comment by akkana** [comment] 2017-04-01 02:10
That's wonderful -- thanks! 0.19 works great. Closing issue.

**Comment by akkana** [comment] 2017-04-01 21:22
Sorry, after working with the new shapewin.py example, I'm still having trouble seeing how to set the input shape. It's probably my misunderstanding, but that example does so much all at once and I can't figure out how to separate its various functions.

The first line where it sets the initial mask seems to do both the input mask and the transparency, somehow:
```
        self.window.shape_mask(shape.SO.Set, shape.SK.Bounding,
                               0, 0, self.add_pm)

I can comment out almost everything else, but as long as that line is there, the window is translucent and mouse events get through. If I comment out that line, the window is opaque and events don't get through.

When I try to apply that to an app that uses pygtk to draw an image, calling it on dpy.create_resource_object("window", self.window.xid). it doesn't seem to matter what I do with the pixmap: it can be one pixel or the size of the image, filled with ones or zeros, but I can never get events passed through. I'll attach a standalone test illustrating the problem (pass it 
[transimagetest.txt](https://github.com/python-xlib/python-xlib/files/887981/transimagetest.txt)

one argument, a local image file).

Please, what is the part of shapewin.py that corresponds to C XShapeCombineMask(dpy, win, ShapeInput, ...) ? I can't figure it out.

**Comment by benoit-pierre** [comment] 2017-04-02 00:00
Neither `examples/shapewin.py` nor `xeyes -shape` work on my machine (Arch Linux, xorg-server 1.19.3-1, nvidia 378.13-4), with or without compton running. They do when run inside Xephyr.

I'm also not sure it's possible to use GTK and python-xlib together like that.

Anyway see [here](https://github.com/python-xlib/python-xlib/compare/master...benoit-pierre:shapewin_test) for a simple example derived from `examples/shapewin.py`: run `python xeyes.py`. The background of the window should pass inputs through. (Again, on my machine, this only work when run inside Xephyr).

**Comment by benoit-pierre** [comment] 2017-04-02 00:09
This might be of interest: [pygtk-cairo-opaque-xshape-window-from-png.py](https://gist.github.com/skriticos/97256). (I can't get it to work under Xephyr, YMMV).

I'm also going to close this, as my example shows python-xlib's support for the XShape extension is working as intended.

**Closed by benoit-pierre** 2017-04-02 00:09 UTC
